#!/usr/bin/env ruby

require "zettel_outline"
require "slop"
require "colorize"

opts = Slop.parse do |o|
  o.separator ""
  o.separator "Required options:"
  o.string '-f', '--file', 'an outline file'
  o.string '-a', '--archive', 'path to your Zettel notes'
  o.string '-o', '--output', 'file to write results to'
  
  o.separator ""
  o.separator "Also available:"
  o.bool '-v', '--verbose', 'verbose output', default: false
  o.on "--version" do
    puts "zettel_outline #{ZettelOutline::VERSION} (#{ZettelOutline::Date}"
    exit
  end
end

def missing_args(msg, opts)
  puts opts
  puts ""
  abort(msg)
end

class Command
  attr_accessor :file, :archive, :output, :verbose
  
  def initialize(opts)
    missing_args("--file required", opts) if opts[:file].nil?
    missing_args("--archive required", opts) if opts[:archive].nil?
    missing_args("--output required", opts) if opts[:output].nil?
    
    opts.to_hash.each do |k, v| send("#{k}=", v) end
  end

  def check_permissions!
    abort("Could not open file '#{@file}'.".red) unless File.readable?(@file)  
    #abort("Could not write to file '#{@output}'.") unless File.writable?(@output)
    abort("Zettel archive does not exist at '#{@archive}'.".red) unless File.directory?(@archive)
  end
  
  def execute
    check_permissions!
    
    in_path = File.expand_path(@file)
    log("Reading in outline from #{in_path} ...")
    content = File.read(@file)
    
    log("Compiling draft from Zettel ...")
    result = ZettelOutline::compile(content, @archive)
    
    out_path = File.expand_path(@output)
    log("Writing to #{out_path} ...")
    File.open(out_path, "w") do |f|
      f.write(ZettelOutline::render(result))
    end
  end
  
  def log(msg)
     puts msg.green if @verbose
  end
end

Command.new(opts).execute
